runtime: python37
entrypoint: gunicorn -b :$PORT wishlist.wsgi

handlers:
  - url: /static
    static_dir: www/static/

  - url: /.*
    script: auto

env_variables:
  TRAVELER_PW: 1Selkies_cb

beta_settings:
  cloud_sql_instances: travel-wishlist-332114:us-central1:wishlist-db
